### ISSUE TITLE
Choose a CSS framework

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/overwatch-team-comps#21]
Do we want to use a CSS framework, and if so, which one? I like them even if we're doing a lovely custom UI because they specify basic styles that are Good Enough ™️, like line-height and font size hierarchies.

I've had good luck with [Bulma](http://bulma.io/) for previous projects. It provides a convenient [grid system](http://bulma.io/documentation/grid/columns/) while also mostly staying out of your way; I don't find myself fighting it a lot to customize styles. I'm open to other options, too -- please share your thoughts!

Other frameworks: [Primer](http://primercss.io/), [Bootstrap](http://getbootstrap.com/)

/cc @justbarreto @summasmiff @smbriones

**Comment by justbarreto** [comment]
I'm very familiar with bootstrap, Yet I'm still open to try other frameworks.

**Comment by smbriones** [comment]
Hey, @cheshire137! Bulma looks pretty good and a bit lighter weight than most. I typically build my own small frameworks and I find that a lot cleaner because we only add what we need and not a lot of extra stuff. However, if an existing framework is best for everyone else, that's cool too. The only downside there is that I find it sometimes more time consuming to customize a framework rather than build one up from scratch. I'm happy to open a PR showing an example of what our own framework might look like.

**Comment by justbarreto** [comment]
I agree with what @smbriones mentioned. Thinking about it, it tends to be more of a hassle to customize bootstrap since we're overwriting most of their stuff. So something custom or lighter would be good.

**Comment by cheshire137** [comment]
> I'm happy to open a PR showing an example of what our own framework might look like.

**Comment by smbriones** [comment]
@cheshire137 Great! 👍

**Comment by cheshire137** [comment]
Fixed with #28.
