### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by ihavenotea** [cheshire137/overwatch-team-comps#4]
I would like to discuss the text the tech stack. 

I know rails really well and am happy to use it. But if we are using react and going heavy from end (which I think makes sense for this), we should probably consider using Node.js and at least talk through the pros and cons thereof.

**Comment by ihavenotea** [comment]
My initial thoughts are that using ES6 for both front end and backend work has some huge advantages and node has better support for waiting xhr requests (better than websockets for push updates).

**Comment by cheshire137** [comment]
My thinking with going Rails for the backend is that I want ActiveRecord because it's so easy to manipulate the database. I've used the [react-rails gem](https://github.com/reactjs/react-rails) before and liked it; it lets me combine my love for React on the front end and Rails on the back end without having a headache over getting ES6 support and JS compilation, because the Rails asset pipeline handles it for you with that gem.

> node has better support for waiting xhr requests (better than websockets for push updates).

Can you tell me what you're envisioning here? I wasn't planning to use websockets. My thinking is React will be convenient for hooking up all the nice JS functionality like "user typed in this field, submit that to the server to save it and flash a little 'saved' message in the UI", while avoiding the callback hell of using plain JS or jQuery.

I was thinking we'd use [whatwg-fetch](https://github.com/github/fetch) for making HTTP requests from the front end. It gives us a nice Promise interface, so we'll do things like `fetch('/maps').then(json => this.onMapsFetched(json)).catch(err => this.onMapsError(err))`. If we had such and our `onMapsFetched` called React's `setState`, the page would re-render as necessary to include our new data.

**Comment by ihavenotea** [comment]
The only cases I can see for heavy push is for real time team updates as players come and go. But I think it is far from a MVP feature and drought with peril. 

It looks like you have done lots of solid prep work here and I am drive by engineering.

**Comment by cheshire137** [comment]
I dunno about _lots_ of prep work, I'm mainly running on my experience of previous side projects built with React! However, there are some new things here that we'll have to figure out as we go, such as using Devise in an otherwise single-page app. Devise likes to create different pages for users to sign up and sign in. Will we ignore those defaults in favor of a sign-in form + OAuth links in a JSX component? Will we keep the separate Devise pages and just use React to manage the authenticated views?
